In [107]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [157]:
vectorizer = CountVectorizer()

In [3]:
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [86]:
test = []
test.append("The apples are sweet. I love the apples. The flowers are beautiful. The. The. The.")
test.append("The bananas are sweet. I love the bananas. The flowers are beautiful. The. The. The.")

In [155]:
test = []
test.append("This is the first document.")
test.append("This is the second second document.")
test.append("And the third one.")
test.append("Is this the first document?")

In [4]:
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

In [156]:
Y = vectorizer.fit_transform(test)

TypeError: fit_transform() missing 1 required positional argument: 'raw_documents'

In [123]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [124]:
Y.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [5]:
X = vectorizer.fit_transform(corpus)

In [6]:
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [7]:
analyze = vectorizer.build_analyzer()

In [8]:
analyze("This is a text document to analyze.") == (['this', 'is', 'text', 'document', 'to', 'analyze'])

True

In [10]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [12]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [75]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()
transformer

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False,
         use_idf=False)

In [79]:
?TfidfTransformer

In [125]:
tfidf = transformer.fit_transform(Y)

In [126]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [127]:
tfidf.toarray()

array([[ 0.        ,  0.4472136 ,  0.4472136 ,  0.4472136 ,  0.        ,
         0.        ,  0.4472136 ,  0.        ,  0.4472136 ],
       [ 0.        ,  0.35355339,  0.        ,  0.35355339,  0.        ,
         0.70710678,  0.35355339,  0.        ,  0.35355339],
       [ 0.5       ,  0.        ,  0.        ,  0.        ,  0.5       ,
         0.        ,  0.5       ,  0.5       ,  0.        ],
       [ 0.        ,  0.4472136 ,  0.4472136 ,  0.4472136 ,  0.        ,
         0.        ,  0.4472136 ,  0.        ,  0.4472136 ]])

In [20]:
tfidf = transformer.fit_transform(X)

0.25259074277046129

In [23]:
max(tfidf.toarray()[0])

0.54197656972645725

In [36]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [40]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [34]:
tfidf[0].max()

0.54197656972645725

In [85]:
tfidf.toarray()

array([[ 0.28867513,  0.28867513,  0.        ,  0.14433757,  0.14433757,
         0.14433757,  0.14433757,  0.8660254 ],
       [ 0.        ,  0.28867513,  0.28867513,  0.14433757,  0.14433757,
         0.14433757,  0.14433757,  0.8660254 ]])

ValueError: not enough values to unpack (expected 2, got 1)

In [41]:
test

['This is the first document.',
 'This is the second second document.',
 'And the third one.',
 'Is this the first document?']

In [43]:
counts = [[3, 0, 1, 9],
          [2, 0, 0, 9],
          [3, 0, 0, 9],
          [4, 0, 0, 9],
          [3, 2, 0, 9],
          [3, 0, 2, 9]]
tfidf = transformer.fit_transform(counts)
tfidf                         
tfidf.toarray()  

array([[ 0.31039787,  0.        ,  0.19113244,  0.93119362],
       [ 0.21693046,  0.        ,  0.        ,  0.97618706],
       [ 0.31622777,  0.        ,  0.        ,  0.9486833 ],
       [ 0.40613847,  0.        ,  0.        ,  0.91381155],
       [ 0.28564983,  0.4290009 ,  0.        ,  0.85694948],
       [ 0.29467041,  0.        ,  0.36289601,  0.88401122]])

In [162]:
test = []
test.append("This is a sample a")
test.append("this is another another example example example")

In [163]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
vectorizer = CountVectorizer()

In [164]:
X = vectorizer.fit_transform(test)

In [165]:
X.toarray()

array([[0, 0, 1, 1, 1],
       [2, 3, 1, 0, 1]], dtype=int64)

In [166]:
vectorizer.get_feature_names()

['another', 'example', 'is', 'sample', 'this']

In [196]:
transformer = TfidfTransformer(smooth_idf = True, sublinear_tf=True)

In [203]:
?TfidfTransformer

In [198]:
transformer

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=True, use_idf=True)

In [199]:
tfidf = transformer.fit_transform(X)

In [202]:
tfidf.toarray()

array([[ 0.        ,  0.        ,  0.50154891,  0.70490949,  0.50154891],
       [ 0.58828823,  0.7291681 ,  0.24721532,  0.        ,  0.24721532]])

In [201]:
transformer.idf_

array([ 1.40546511,  1.40546511,  1.        ,  1.40546511,  1.        ])